### ISSUE TITLE
[Item] Steel Plate Helm Recipe

### ISSUE THREAD

**Issue by XSNomad** [ZhengPeiRu21/mod-individual-progression#10]
WOTLK - The Steel Plate helm was 

> upgraded to a blue
> added 24 STR
> had 80 bonus armor
> required a Citrine to craft. 

Classic

> White
> No STR
> No Citrine

Expected:
Remove Requirement for Citrine
Remove Bonus Armor 
OR (preferred)
Add 24 STR

https://wotlkdb.com/?item=7922
https://classic.wowhead.com/item=7922/steel-plate-helm

**Comment by XSNomad** [comment]
Preferred Fix

```
DELETE FROM `item_template` WHERE (`entry` = 7922);
INSERT INTO `item_template` (`entry`, `class`, `subclass`, `SoundOverrideSubclass`, `name`, `displayid`, `Quality`, `Flags`, `FlagsExtra`, `BuyCount`, `BuyPrice`, `SellPrice`, `InventoryType`, `AllowableClass`, `AllowableRace`, `ItemLevel`, `RequiredLevel`, `RequiredSkill`, `RequiredSkillRank`, `requiredspell`, `requiredhonorrank`, `RequiredCityRank`, `RequiredReputationFaction`, `RequiredReputationRank`, `maxcount`, `stackable`, `ContainerSlots`, `StatsCount`, `stat_type1`, `stat_value1`, `stat_type2`, `stat_value2`, `stat_type3`, `stat_value3`, `stat_type4`, `stat_value4`, `stat_type5`, `stat_value5`, `stat_type6`, `stat_value6`, `stat_type7`, `stat_value7`, `stat_type8`, `stat_value8`, `stat_type9`, `stat_value9`, `stat_type10`, `stat_value10`, `ScalingStatDistribution`, `ScalingStatValue`, `dmg_min1`, `dmg_max1`, `dmg_type1`, `dmg_min2`, `dmg_max2`, `dmg_type2`, `armor`, `holy_res`, `fire_res`, `nature_res`, `frost_res`, `shadow_res`, `arcane_res`, `delay`, `ammo_type`, `RangedModRange`, `spellid_1`, `spelltrigger_1`, `spellcharges_1`, `spellppmRate_1`, `spellcooldown_1`, `spellcategory_1`, `spellcategorycooldown_1`, `spellid_2`, `spelltrigger_2`, `spellcharges_2`, `spellppmRate_2`, `spellcooldown_2`, `spellcategory_2`, `spellcategorycooldown_2`, `spellid_3`, `spelltrigger_3`, `spellcharges_3`, `spellppmRate_3`, `spellcooldown_3`, `spellcategory_3`, `spellcategorycooldown_3`, `spellid_4`, `spelltrigger_4`, `spellcharges_4`, `spellppmRate_4`, `spellcooldown_4`, `spellcategory_4`, `spellcategorycooldown_4`, `spellid_5`, `spelltrigger_5`, `spellcharges_5`, `spellppmRate_5`, `spellcooldown_5`, `spellcategory_5`, `spellcategorycooldown_5`, `bonding`, `description`, `PageText`, `LanguageID`, `PageMaterial`, `startquest`, `lockid`, `Material`, `sheath`, `RandomProperty`, `RandomSuffix`, `block`, `itemset`, `MaxDurability`, `area`, `Map`, `BagFamily`, `TotemCategory`, `socketColor_1`, `socketContent_1`, `socketColor_2`, `socketContent_2`, `socketColor_3`, `socketContent_3`, `socketBonus`, `GemProperties`, `RequiredDisenchantSkill`, `ArmorDamageModifier`, `duration`, `ItemLimitCategory`, `HolidayId`, `ScriptName`, `DisenchantID`, `FoodType`, `minMoneyLoot`, `maxMoneyLoot`, `flagsCustom`, `VerifiedBuild`) VALUES
(7922, 4, 4, -1, 'Steel Plate Helm', 16093, 3, 0, 0, 1, 41522, 8304, 1, -1, -1, 43, 40, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 4, 24, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 421, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -1, 0, -1, 0, 0, 0, 0, -1, 0, -1, 0, 0, 0, 0, -1, 0, -1, 0, 0, 0, 0, -1, 0, -1, 0, 0, 0, 0, -1, 0, -1, 0, '', 0, 0, 0, 0, 0, 6, 0, 0, 0, 0, 0, 80, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 125, 80, 0, 0, 0, '', 45, 0, 0, 0, 0, 12340);
```

**Comment by ZhengPeiRu21** [comment]
It is desired for all items to be accurate to Vanilla values. It seems the bonus armor here is incorrect; I will fix the item to remove the bonus armor.

The crafting recipe should have been changed. Please note that crafting recipe changes requires using the optional patches on both the client and the server. Are you using the optional patches?

**Comment by ZhengPeiRu21** [comment]
When I review my notes of the items change I see why the armor value was not modified. I have noted that armor values and block values were changed in later patches because the formula of using them changed - they were changed to have about the same effect as before the change. So I did not modify these values back to their Vanilla version. However, I did not note exactly which patch changed this, so I am not able to double-check exactly how the formula was change. If someone is able to find the patch notes for when this change is occur, we can double-check.

**Comment by ZhengPeiRu21** [comment]
I done more research and could not find any explanation of the armor and block increase as anything except a buff, so I think it is appropriate to set back to original values. If we're able to find more explanation of the change due to a different formula, we can re-consider, but for now, I have changed all Block and Armor values to their original. Fixed in https://github.com/ZhengPeiRu21/mod-individual-progression/commit/8a61196ebce573c3b27487b31c6679edb4be6b1a.
