### ISSUE TITLE
Old World still Elite if deactivated!

### ISSUE THREAD

**Issue by profindi** [ZhengPeiRu21/mod-individual-progression#124]
So i deactivated the module in the config, but in the old world all mobs are still elite in front of the dungeons ?
also it still takes the values from IndividualProgression.VanillaPowerAdjustment ?

**Comment by ZhengPeiRu21** [comment]
I apologize that the setting description was not clear. AzerothCore modules are not able to control or undo database changes through config options, so disabling it in the config will not restore NPC status. To remove the changes from the module, it will be necessary to remove it and clear your world database so that it repopulates without the module's change. I have updated the documentation to clarify. 

Power adjustments still taking place even when disabled was a bug that I have fixed as well. Thank you for reporting the issue! Please let me know if you have any other questions.

These changes can be found in (https://github.com/ZhengPeiRu21/mod-individual-progression/commit/bb5ccde9d3498faf7bcbb4824e6780df9f9136ca).
