### ISSUE TITLE
[Suggestion] Config options to remove attunement requirements

### ISSUE THREAD

**Issue by Dreathean** [ZhengPeiRu21/mod-individual-progression#152]
It would be a nice feature to have a config options to remove attunement requirements, especially for those looking to use this module alongside PlayerBots once those are more stable, so that you wouldn't have to worry about the AI needing to get attuned for each raid/TBC heroics.

**Comment by sihensel** [comment]
Sorry to necro-bump, but since this issue is still open, I figured I leave a quick comment.

After running into the same issue I did some testing with the Playerbots module regarding raid attunements. Turns out you can still run the instance even if the bots are not attuned.
While they cannot follow you _through_ the instance portal without the attunement, you can still zone in by yourself and then use the `/raid summon` chat command, which teleports all bots to you, independent of whether they are attuned or not.
Likewise, It is also possible to invite new bots to your party while you are already inside, which also teleports them to you, bypassing the attunement requirement.

Or ultimatively, if you want to make sure the bots are attuned, you can update the `acore_characters.character_queststatus_rewarded` table with the respective character and quest IDs.

**Comment by Dreathean** [comment]
Ah yes I did figure this out when I started playing around with them more, thank you for the help though! I will close this out now.
