### ISSUE TITLE
Tranq shot and Vish Kozus

### ISSUE THREAD

**Issue by Grimfeather** [ZhengPeiRu21/mod-individual-progression#154]
A few small issues I've encounted.

Vish Kozus at the Cenarion Hold is hidden in progression tier 1.
Can't turn in the quest "Wanted - Deathclasp terror of the sands".
(in GM mode we can hand it in though)

hunter: tranquillizing shot available at trainer, used to be drop in molten core
https://www.wowhead.com/wotlk/item=16665/tome-of-tranquilizing-shot
I noticed you removed other spells like Gift of the Wild from trainers, so this one should probably be removed as well.

**Comment by ZhengPeiRu21** [comment]
Thank you again for your contributions. I've fixed Tranq Shot in https://github.com/ZhengPeiRu21/mod-individual-progression/commit/e0f145c0e7dc32340ba2d1a4b6e6dfde47fd15c5.

Vish Kozus is part of AQ40 content, and offers several quests that provide AQ40 catch up gear badges. This does unfortunately mean that the quest mentioned cannot be completed until he is available. I think the solution would either be to phase the quest starting object as well, so that there is not an uncompletable quest available, or to move the completion to a different NPC - this wouldn't be accurate to Vanilla but would make the quest completable while the gear is still relevant. What are your thoughts?

**Comment by Grimfeather** [comment]
You sure Vish Kozus starts quests as well?
https://www.wowhead.com/classic/npc=15182/vish-kozus#ends;mode:normal
As far as I can tell he only ends quests. 

Vargus, the blacksmith handles the catch up gear badges quests.

**Comment by ZhengPeiRu21** [comment]
Resolved in https://github.com/ZhengPeiRu21/mod-individual-progression/commit/06a2ecd73a6f62c7674999986819626cceffd8bf.
