### ISSUE TITLE
Possible minor installation instruction error

### ISSUE THREAD

**Issue by Grimfeather** [ZhengPeiRu21/mod-individual-progression#163]
I've updated my server today and was going through your installation instructions again
https://github.com/ZhengPeiRu21/mod-individual-progression/wiki/How-to-Install

At step 10b there may be a small error.
You mention: "There should be a total of 5 dbc files overwritten."
I can only find 4 dbc files inside the dbc zip file.

One more thing.
I was getting these errors when starting the worldserver
https://i.gyazo.com/96828fbc794b5d8ef1d6317a10825da1.png
I've simply done what the errors said was wrong and changed those values.
There seems to be no issue doing so and it got rid of the errors.
But maybe there is something else going on I'm not aware of.

**Comment by ZhengPeiRu21** [comment]
Thank you for pointing out the error in the documentation; it is out of date. I have updated it.

Regarding the errors in the worldserver, those are intentional - the module makes changes to several items to revert them to their Vanilla state, such as Rogue poison reagents which were made into Junk in WotLK. Changing the values back will restore them to their WotLK item classes. AzerothCore currently incorrectly shows this error message even when DBC.EnforceItemAttributes is set to 0. I plan to create a PR to fix this behavior.

I once again appreciate your frequent reporting of issues! Please let me know if you come across anything else.
