### ISSUE TITLE
Jandice Barov spell Curse of Blood increasing physical damage taken by 500

### ISSUE THREAD

**Issue by Divreus** [ZhengPeiRu21/mod-individual-progression#167]
Jandice Barov's illusions obliterated my girlfriend and I in Scholomance scaled down to 2 players with the default autobalance settings (if that's relevant).
The reason, I suspect, was related to a tooltip informing me that Curse of Blood was increasing my physical damage taken by 500.
Apologies if this is an Azerothcore bug or even Vanilla behavior, I'm not very familiar with WoW.
However, my girlfriend was very insistent that this isn't how the fight is supposed to be, and I can't find anything online about the debuff increasing damage taken by that much.
The release I'm playing on was downloaded on July 20th.

**Comment by ZhengPeiRu21** [comment]
Thank you very much for reporting this issue. It does look like Jandice's illusions are indeed using the wrong spell - they are using Curse of Blood (24673) instead of Curse of Blood (16098). The correct version is much weaker. This is an AzerothCore issue, so I will fix it upstream and mark this as resolved once completed.

**Comment by ZhengPeiRu21** [comment]
The AzerothCore fix has been merged. This issue should now be resolved. Please let me know if you see any more issues! Thanks again for your report.
