### ISSUE TITLE
Shy-Rotam quest

### ISSUE THREAD

**Issue by Grimfeather** [ZhengPeiRu21/mod-individual-progression#170]
Both Shy and Sian do a crazy amount of damage. 
They take me out in 3 seconds while I'm in Dire Bear form with lvl 60 blue dungeon gear with 4.7k health.

I found this in vanilla_creature_values.sql

/*  Shy-Rotam  */
UPDATE `creature_template` SET `rank` = 1, `DamageModifier` = 5.3, `HealthModifier` = 4.5,

/*  Sian-Rotam  */
UPDATE `creature_template` SET `rank` = 1, `DamageModifier` = 5.45, `HealthModifier` = 4.5,

You sure those damage modifiers are correct? Because I think they're wrong.

Another issue is that they both spawn together after placing the sacred frostsaber meat,
Shy-Rotam is supposed to spawn first and calls for Sian-Rotam when she gets to about 25% health.
check this YT video for reference:  https://www.youtube.com/watch?v=ljRpv0ubdmU
but this is probably an issue for AzerothCore.

**Comment by Saniok88** [comment]
It is not related to the Individual Progression module. AzerothCore, unfortunately, is quite rough, has various bugs everywhere, even in the core itself. ChromieCraft server is an official AzerothCore server, which merges updates from it every week. I have some experience playing on it and can describe some bug examples, that exist there:

1) Geo data (creature navigation meshes) issues, like ignoring LOS, running and passing walls. This is one of the main things that has to be fixed ASAP, and one of those things, that differentiates a good server and a bad server.

2) If you jump while swimming, you sometime lose "swim gravitation" and fall to to bottom of lake (after that you still can swim back to surface). Using mage Blink will always result in that bug.

3) Also for some reason they have very large radius of something, that i dont know how it is named, but i will describe the effect. When you want to attack mob from a distance to pull a mob away from his "friends", there exist a specific radius, in which his friends will also join the fight and get aggroed too. Radius of this effect is too high on ChromieCraft (and probably AC) and should be reduced by 1/3. It is annoying, because you sometime pull 2-4 mobs, when you expect to pull just 1-2 at most, this also makes clearing some caves with high mob density much harder or impossible to solo.

4) A lot of Database data is incorrect or unpolished (not blizzlike), some values are rough, as lazy placeholders. For example if you try to solo "Fizzle Darkstorm" in Durotar (i dont remember it is either a quest name or a mob needed for that quest), you literally can not do it, because he simply does not patrol and always stays near other mobs, so you have no chances to pull him separate (especially with high radius of previously reported (# 3) issue).

5) on vanilla content (1-60 levels) rare mobs dont drop any bonus loot (no green drops from them), or at least many among them do not drop bonus loot.

All of this is not something old or outdated, i literally leveled there just few weeks ago, started just mid september with RAF bonus.

I reported # 3, officially in Github half year ago or so, currently it is not closed, not reviewed, probably just ignored for a while. I hope, that they will begin fixing these issues in a future, when they fix TBC and WOTLK progression content. So the server core is way more bugged, than, for example, VMangos core, or any other, they still need some time to catch up to the 2020+ standards. But it has some upsides too - more active development (but not competent on priorities, imho), Module system is the main upside, this alone will make it potentially by far the best core ever in a future, when they fix core and DB/content bugs to catch up to other cores at default content quality. Currently the only upside it is having - is the module system, which allows to program custom gameplay systems, new game mechanics, new character progression systems. Which would not be possible (or would be hard to implement, maintain, develop and fix) on other cores. Example of interesting mechanics - is the WoW Synastria server, their custom perks and equipment attunement systems.

**Comment by Grimfeather** [comment]
"It is not related to the Individual Progression module."

the first part about the damage modifiers is related to this module.

**Comment by Saniok88** [comment]
I have done this quest on other AC based server, and IIRC it was not elite, not sure if it did any bonus damage compared to normal mob of same level, so yeah, it should be related to the Individual Progression module.

**Comment by Grimfeather** [comment]
I just checked vanilla_creature_values.sql

/*  Shy-Rotam  */
UPDATE `creature_template` SET `rank` = 1, `DamageModifier` = 3.0, `HealthModifier` = 4.5, `ManaModifier` = 2.0, `BaseAttackTime` = 1500, `RangeAttackTime` = 1265 WHERE `entry`=10737;

/*  Sian-Rotam  */
UPDATE `creature_template` SET `rank` = 1, `DamageModifier` = 4.25, `HealthModifier` = 4.5, `RangeAttackTime` = 1265 WHERE `entry`=10741;

Both now have lower damage modifiers.
They still spawn together, but that's an upstream AzerothCore issue
