### ISSUE TITLE
Various vendor issues (TBC/WotLK items, missing etc.)

### ISSUE THREAD

**Issue by ajgration** [ZhengPeiRu21/mod-individual-progression#180]
I'll keep adding to this as I find more. Doing a fresh playthrough and this is what I've found so far. I opted not to include things I found like JC recipes/inscription mats as the mod has chosen to keep those professions in the game so it makes sense for them to be there.

- [x] Mani Winterhoof (3010) selling Enchanted Vial (40411)
- [x] Sarah Killian (4599) selling Jeweler's Kit (20815) and Simple Grinder (20824)
- [x] Patrice Dwyer (3551) selling Instant Poison VIII (43230), Instant Poison IX (43231), Deadly Poison VIII (43232), Deadly Poison IX (43233), Wound Poison VI (43234), Wound Poison VII (43235), and Anesthetic Poison II (43237)
- [x] Ezekiel Graves (4585) selling Instant Poison VIII (43230), Instant Poison IX (43231), Deadly Poison VIII (43232), Deadly Poison IX (43233), Wound Poison VI (43234), Wound Poison VII (43235), and Anesthetic Poison II (43237)
- [x] Thomas Mordan (4562) selling Flintweed Seed (22147), Wild Quillvine (22148), Wild Spineleaf (44605), Starleaf Seed (44614), and Devout Candle (44615)
- [x] Hannah Akeley (4575) selling Flintweed Seed (22147) and Wild Quillvine (22148)
- [x] Jeeda (4083) selling Flintweed Seed (22147) and Wild Quillvine (22148)
- [x] Engineer Torquespindle (25082) selling Flintweed Seed (22147) and Wild Quillvine (22148)
- [x] Zarena Cromwind (2482) selling Freshly-Squeezed Lemonade (23161) and Friendship Bread (23160)
- [x] Qixdi Goodstitch (2849) selling Noble's Elementium Signet (37934)

- [x] PVP mounts should require rank 11 (Commander/Lieutenant General)
- [x] All iterations of Insignia of the Horde/Alliance should require Rank 2 (Corporal/Grunt), and be itemlevel 60 instead of 0
- [x] Kelm Hargunth (14754) not selling anything for me, blank vendor window. I assume this is the same for Alliance and other battleground vendors.
- [X] PVP gear ≤60 and mounts should cost gold instead of honor points. I can understand and would probably prefer keeping this as is though, else there's nothing to spend honor points on in vanilla content.

**Comment by ZhengPeiRu21** [comment]
Thanks for these detailed reports! This is very helpful - I'll try to make my way through fixing these. I hope you don't mind if I edit your comment into a checklist to track progress.

**Comment by ZhengPeiRu21** [comment]
I do plan to keep the honor cost for vanilla PvP items for the reasons you've mentioned. If anyone feels otherwise and would like an optional gold patch, please let me know.

**Comment by ajgration** [comment]
No worries, sounds good to me!

**Comment by ZhengPeiRu21** [comment]
Several of these issues have been resolved in https://github.com/ZhengPeiRu21/mod-individual-progression/commit/3ee5833b37bf81069d8af672ae679f412b55886f. I have checked the related checkboxes in the original post.

**Comment by Grimfeather** [comment]
I made a pull request for some of the issues here

some notes:

Zarena Cromwind (2482) 
https://www.wowhead.com/classic/npc=2482/zarena-cromwind
according to wowhead comments she does sell the reported items during vanilla.
"These appeared after the scourge invasion event."

I've added the rank 2 requirement to the insignia pvp trinkets, but NOT the level 60 requirement.
I'm not so sure they require level 60. I remember using this trinket while leveling.

I looked into Kelm Hargunth (14754), but I haven't found a list of items he sells in vanilla.
https://www.wowhead.com/classic/npc=14754/kelm-hargunth#comments
in the comments here it says:
Food, drinks, Potions, and trinkets = friendly status
Cloak, Ring, Necklace = honored status
Staff, Sword, Dagger, Bow = Revered
Tabbard, Bracers = Exalted status

I could make a calculated guess on what should be for sale, but maybe someone can find a list

**Comment by ajgration** [comment]
Cheers mate. Ive been busy and haven't played in a while so thanks for getting round to these! 

You're right about the insignia, it shouldn't have a level requirement, it was just the item level that was reading 0 that I was referring to.

As for Kelm, I'm pretty sure that this list here is correct in terms of items/reputations needed. https://www.wowhead.com/classic/guide/warsong-outriders-warsong-gulch-reputation-wow-classic

Thanks!

**Comment by Grimfeather** [comment]
I see. yes strange. A few of the class pvp trinkets do have iLevel 60. but most do not.
I could fix it here, but I believe this should be fixed by AzerothCore itself, not this module.

this would fix it:

/*  Insignia of the Alliance (mage)  */
UPDATE `item_template` SET `ItemLevel` = 60 WHERE entry=18859;

/*  Insignia of the Alliance (priest)  */
UPDATE `item_template` SET `ItemLevel` = 60 WHERE entry=18862;

/*  Insignia of the Alliance (druid)  */
UPDATE `item_template` SET `ItemLevel` = 60 WHERE entry=18863;

/*  Insignia of the Alliance (paladin)  */
UPDATE `item_template` SET `ItemLevel` = 60 WHERE entry=18864;

/*  Insignia of the Alliance (shaman)  */
UPDATE `item_template` SET `ItemLevel` = 60 WHERE entry=29593;

/*  Insignia of the Horde (warrior)  */
UPDATE `item_template` SET `ItemLevel` = 60 WHERE entry=18834;

/*  Insignia of the Horde (shaman)  */
UPDATE `item_template` SET `ItemLevel` = 60 WHERE entry=18845;

/*  Insignia of the Horde (hunter)  */
UPDATE `item_template` SET `ItemLevel` = 60 WHERE entry=18846;

/*  Insignia of the Horde (mage)  */
UPDATE `item_template` SET `ItemLevel` = 60 WHERE entry=18850;

/*  Insignia of the Horde (priest)  */
UPDATE `item_template` SET `ItemLevel` = 60 WHERE entry=18851;

/*  Insignia of the Horde (druid)  */
UPDATE `item_template` SET `ItemLevel` = 60 WHERE entry=18853;

/*  Insignia of the Horde (paladin)  */
UPDATE `item_template` SET `ItemLevel` = 60 WHERE entry=29592;

--------

I'll have another look at the Kelm's inventory. Thanks for the link.

**Comment by Grimfeather** [comment]
ZhengPei, could you please have a look at this and possibly tell me why the items I added to Kelm aren't showing up in game?
I delete my WDB cache items to see if that was the problem, but that wasn't it.

https://github.com/Grimfeather/mod-individual-progression/compare/master...WSG-pvp-vendors

**Comment by ZhengPeiRu21** [comment]
> ZhengPei, could you please have a look at this and possibly tell me why the items I added to Kelm aren't showing up in game? I deleted my WDB cache to see if that was the problem, but that wasn't it.
> 
> [Grimfeather/mod-individual-progression@master...WSG-pvp-vendors](https://github.com/Grimfeather/mod-individual-progression/compare/master...WSG-pvp-vendors)

Sure, I should have some time to look into this tomorrow. Sorry for being a bit swamped recently. Thank you for your PRs!

**Comment by Grimfeather** [comment]
https://i.gyazo.com/d7bd24f155dba49fc306d6205be2d5e3.jpg

Ok, so, when I make an alternate version of Kelm, with the EXACT same information as the original (!?) he does show his inventory.
I don't understand this.

**Comment by Grimfeather** [comment]
All these issues have now been fixed. Can this be closed?

**Comment by ajgration** [comment]
> All these issues have now been fixed. Can this be closed?

Legend.
