### ISSUE TITLE
[Suggestion] Optional Variant for WOTLK Item Restoration

### ISSUE THREAD

**Issue by StraysFromPath** [ZhengPeiRu21/mod-individual-progression#199]
Doing dungeons like deadmines/wailing caverns/gnomeregan and the bosses dropping nothing but junk greys is vanilla accurate but it's not an enjoyable gameplay experience.

If the intent is to progress through classic - tbc - wotlk, I would prefer to enjoy and have fun with these iconic early game and early dungeon items.

I'd love for a "wotlk variant items table" option/config which puts equipment back to wotlk stats. My current solution is to manually revert items when I come across them but this is long, slow, and awkward.

**Comment by ZhengPeiRu21** [comment]
Thank you for the suggestion. This should be possible by just not running https://github.com/ZhengPeiRu21/mod-individual-progression/blob/master/sql/world/base/item_changes.sql. Because there's simple no way to make database changes config options, especially for something as extensive as this, I would just recommend not running this file. Please let me know if you have any questions!
