### ISSUE TITLE
[Optional File] Wrong Sign in Auberdine

### ISSUE THREAD

**Issue by StraysFromPath** [ZhengPeiRu21/mod-individual-progression#216]
![image](https://github.com/ZhengPeiRu21/mod-individual-progression/assets/119371540/617a631c-79a7-4cbb-b3f4-1a35ba021405)

The optional changes to change the boats don't change the signs.

**Comment by Defalion** [comment]
Yeah right, I noticed that! The boat goes to Menethil Harbour. 
I might add that I think when in Menethil - you can sometimes have 2 boats arrive at the same time at the same place, the one that takes you to Auberdine + the one that ( i think ) takes you to northrend

**Comment by ZhengPeiRu21** [comment]
Thank you very much for reporting this issue! This is fixed in https://github.com/ZhengPeiRu21/mod-individual-progression/commit/751941e07e03094be8c17fdc48fbe0d13699717e.

Regarding the boats occasionally overlapping: unfortunately, this is a known issue and can't be solved without client edits. The harbor is used by two different boats since a boat to Northrend was added in WotLK and they do occasionally overlap. Please see the original issue here: https://github.com/ZhengPeiRu21/mod-individual-progression/issues/46.
