### ISSUE TITLE
Boat from Menethil Harbor bug

### ISSUE THREAD

**Issue by kekeshgreen** [ZhengPeiRu21/mod-individual-progression#218]
Sometimes a second boat shows up in the first phase, that looks like the boat to Northrend and covers up the boat to Auberdine. It dumps you in the ocean if you go on it.

**Comment by ZhengPeiRu21** [comment]
Thank you for opening this issue. Unfortunately, this is a known issue and can't be solved without client edits. The harbor is used by two different boats since a boat to Northrend was added in WotLK and they do occasionally overlap. Please see the original issue here: https://github.com/ZhengPeiRu21/mod-individual-progression/issues/46
