### ISSUE TITLE
Jeweller's Kit Missing from ~20 NPCs

### ISSUE THREAD

**Issue by StraysFromPath** [ZhengPeiRu21/mod-individual-progression#219]
https://www.wowhead.com/tbc/item=20815/jewelers-kit

Ever since jewelcrafting existed in 2.0.1 you could buy jewelling kits in many classic npcs.

**Comment by ZhengPeiRu21** [comment]
Thank you for the report. This is the intended behavior; Vanilla NPCs have been reverted to their 1.12 state. Since jewelcrafting training is only available in TBC zones anyway (including TBC race starting zones,) I don't think it is a major concern that Jeweler's Kits are only available there as well. Please let me know if you feel strongly otherwise.

**Comment by StraysFromPath** [comment]
> Thank you for the report. This is the intended behavior; Vanilla NPCs have been reverted to their 1.12 state. Since jewelcrafting training is only available in TBC zones anyway (including TBC race starting zones,) I don't think it is a major concern that Jeweler's Kits are only available there as well. Please let me know if you feel strongly otherwise.

Because you chose to let Jewelcrafting be available for all chars from level 1 you should keep the Jewellers Kits.

The item is harmless/flavour/does no harm to a vanilla experience.

Removing it damages the TBC experience.

Kalimdor and Eastern Kingdoms are TBC zones with Kharazan/Caverns of Time content.
