### ISSUE TITLE
 Added a personal progress module, unable to queue random books.

### ISSUE THREAD

**Issue by alexyang-sea** [ZhengPeiRu21/mod-individual-progression#235]
I'd like to ask if after adding the Personal Progress MOD, I'm unable to select any level of random books, and I keep getting a prompt saying it's not installed.
![22](https://github.com/ZhengPeiRu21/mod-individual-progression/assets/137014157/4e153874-1e6b-4ee6-8b26-03c860656b1b)

**Comment by ZhengPeiRu21** [comment]
This is intended behavior with the default config options. To re-enable, please change this setting in your config:
IndividualProgression.SimpleConfigOverride = 1
to
IndividualProgression.SimpleConfigOverride = 0

This will change the module to respect your worldserver.conf rather than overriding some config values for the intended experience.
I hope that helps! Please let me know if you continue to see any other problems.
