### ISSUE TITLE
Repeatable Quest do not give XP

### ISSUE THREAD

**Issue by XSNomad** [ZhengPeiRu21/mod-individual-progression#26]
This is part of Core which is unlike Vanilla: 
https://www.azerothcore.org/wiki/quest_template#rewardxpdifficulty
`If the quest is repeatable, XP will be given only once. `

Classic should give XP
https://classic.wowhead.com/quest=3803/morrowgrain-to-darnassus

WOTLK this was removed
https://www.wowhead.com/wotlk/quest=3803/morrowgrain-to-darnassus

Additional Notes
Troll Necklace Bounty 
Classic
https://classic.wowhead.com/quest=2881/troll-necklace-bounty - Repeatable

WOTL
Not Repeatable
https://www.wowhead.com/wotlk/quest=2881/troll-necklace-bounty

Fix for this quest in comments.

**Comment by XSNomad** [comment]
Troll Necklace Bounty
Diff
`UPDATE `quest_template_addon` SET `SpecialFlags` = 1 WHERE (`ID` = 2881);`

Full Query
`DELETE FROM `quest_template_addon` WHERE (`ID` = 2881);
INSERT INTO `quest_template_addon` (`ID`, `MaxLevel`, `AllowableClasses`, `SourceSpellID`, `PrevQuestID`, `NextQuestID`, `ExclusiveGroup`, `RewardMailTemplateID`, `RewardMailDelay`, `RequiredSkillID`, `RequiredSkillPoints`, `RequiredMinRepFaction`, `RequiredMaxRepFaction`, `RequiredMinRepValue`, `RequiredMaxRepValue`, `ProvidedItemCount`, `SpecialFlags`) VALUES
(2881, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1);
`

**Comment by ZhengPeiRu21** [comment]
Thank you, I always think I know all of the changes since Vanilla but did not know this one! I have add special handling for these two quests to allow them to repeat and receive the rewards multiple times, including XP in: https://github.com/ZhengPeiRu21/mod-individual-progression/commit/c552a84d4da6ae177e9941378290dc05d544ab0c. Please let me know if there are other quests that need this special handling as well.
