### ISSUE TITLE
[Question] How to trigger progession events/world events like Ahn Qiraj Gates or Burning Portal Opening?

### ISSUE THREAD

**Issue by StraysFromPath** [ZhengPeiRu21/mod-individual-progression#276]
Title

**Comment by ZhengPeiRu21** [comment]
Thanks for the suggestion. There have been similar requests in the past (https://github.com/ZhengPeiRu21/mod-individual-progression/issues/215). Because world events impact the world and not individual players, they aren't implemented as part of the individual progression module. I like the idea of re-implementing these events in a way that they can be adjusted for individual players, but they would need to be extensively reworked, so this is not a priority at the moment.

The default AzerothCore version of world events is unchanged by the module, and can be activated using gm commands (ie., `.event start #event_id`). I'm not sure what the state of these events are upstream.

Due to the related linked issue being posted first, I will close this issue and discussion can continue there.
