### ISSUE TITLE
Players are able to enter raids they should have no access to

### ISSUE THREAD

**Issue by DrNefarius** [ZhengPeiRu21/mod-individual-progression#299]
So my IndividualProgression.ProgressionLimit and IndividualProgression.StartingProgression are both set to 2 (so MC and Onyxia are enabled).
However, a player reported to me that he could enter Blackwing Lair. I double checked, and yes, he did indeed enter Blackwing Lair without any problems. According to individualProgression.h Blackwing Lair should only be enabled at progression state >= 3.

I tested a bit more and when I set both variables to 1 instead of 2, the players were not able to enter Blackwing Lair anymore. Onyxia stayed available tho. So it seems that state = 1 enables both MC and Onyxia and 2 enables Blackwing Lair, so the doc seems to be shifted by 1 and MC and Onyxia share the same state.

**Comment by ZhengPeiRu21** [comment]
Thanks for filing an issue. This is working as intended, though the design intent isn't entirely clear from the enum values in the header. Onyxia is available without any previous progression, as was the case at Vanilla launch. Entering Blackwing Lair requires Molten Core to be completed, but doesn't require Onyxia to be defeated. However, if players have not defeated Onyxia, they will not have the Onyxia scale cloak required to defeat Nefarion, so BWL can't be completed either. This was such a nice flavor of natural RPG-style tier progression that I left it this way rather than simply restricting access if Onyxia hasn't been defeated.
Here is a page from the documentation that describes the tiers more clearly:
[https://github.com/ZhengPeiRu21/mod-individual-progression/wiki/List-of-Progression-Tiers](https://github.com/ZhengPeiRu21/mod-individual-progression/wiki/List-of-Progression-Tiers)

I hope that clears things up! Please let me know if you have any further questions.
