### ISSUE TITLE
Dungeon set 2

### ISSUE THREAD

**Issue by Remakbna** [ZhengPeiRu21/mod-individual-progression#300]
It is impossible to complete the Three Kings of Flame (8961) quest before tier 4 because summoning The Duke of Cynders requires components that are given for completing quests in Silithus that are not available until tier 4 is unlocked. For example: Medallion of Station (8333). Please fix this.

**Comment by ZhengPeiRu21** [comment]
Aurel Goldleaf and Huum Wildmane have special phasing where if the `IndividualProgression.AllowEarlyDungeonSet2` option in the config is set to 1 (which it is by default,) they will always be available regardless of the player's progression specifically so that these quests can be accomplished. Have you changed this option in your config?

Also please make sure that you've done the prerequisites for the quests. The quest chain begins with (https://www.wowhead.com/classic/quest=8331/aurel-goldleaf) and requires Friendly status with Cenarion Circle.

**Comment by Remakbna** [comment]
Спасибо за объяснение. проблемма была в репутации. Прошу прощения.
