### ISSUE TITLE
Autobalance doesn't work on Onyxias Lair.

### ISSUE THREAD

**Issue by Thatharis** [ZhengPeiRu21/mod-individual-progression#305]
Title. I saw that this is fixed with Naxx 40, so I imagine that this is an error just like it.
This also doesn't seem to work with Naxx 40. Aboms still have around 80k health or so.

**Comment by atrapalis** [comment]
This has been brought up a few times before, and should have been fixed in a previous update (including Naxx 40).
Could you please check the discussion in issue 263?

The fix requires a database/SQL update which is I do not think is run automatically when you upgrade this module.
For 40-man Onyxia the SQL file that fixes this is: sql/world/base/dungeon_onyxia.sql

**Comment by Thatharis** [comment]
Fixed it by updating the SQLs, thanks!
