### ISSUE TITLE
Quest: A Better Ingredient - Rewards

### ISSUE THREAD

**Issue by Grimfeather** [ZhengPeiRu21/mod-individual-progression#310]
https://www.wowhead.com/classic/quest=9053/a-better-ingredient

the rewards for this quest haven't been changed back to vanilla versions.

https://www.wowhead.com/classic/item=22272/forests-embrace
https://www.wowhead.com/classic/item=22458/moonshadow-stave

I've checked item_changes.sql and both these items are not in it.
the 3rd reward for this quest stayed the same.

Maybe also worth  mentioning, this quest is available right now from the start. progression tier 1.
originally this quest was added in patch 1.10.0, look under druid changes here:
https://wowwiki-archive.fandom.com/wiki/Patch_1.10.0
I think this is progression tier 5. I like it being available early though, so I prefer it to stay like it is.

**Comment by ZhengPeiRu21** [comment]
Thank you for the issue report. These items were actually not changed in WotLK, but the underlying way the engine handles certain stats was changed, hence the description being different. You can see that the effect spell used (https://www.wowhead.com/wotlk/spell=18036/increase-healing-55) is the same. In WotLK, spell power also affects healing at a 2:1 ratio, so this ends up having the same effect on healing. It does increase spell damage which it wouldn't do pre-WotLK, but this is part of the WotLK class design and is the type of change that is considered in the module's tuning.

Regarding the quest being available in the initial progression tier, I would say this is a case where it makes the most sense for it to be available early. It fits best into the game flow here, and the rewards would be obsolete if it were only available after raids. This is a case of it being "additional level content" rather than "catch up content."

I hope that all makes sense! Please let me know if you disagree or have other concerns.

**Comment by Grimfeather** [comment]
I agree. 

Thanks for the explanation on spell damage. I knew this, but somehow I forgot. I'm getting old.
