### ISSUE TITLE
Few ideas

### ISSUE THREAD

**Issue by Eldatur** [ZhengPeiRu21/mod-individual-progression#32]
Hello, just found this module a few days ago I was just starting a completionist/progression run from 1.12.1 and onwards but This is way better! This way I don’t have to mess with different servers and clients.

I was thinking a bit regarding spells and talents. Maybe it could be tied/locked to progression that before you hit Outland/TBC then you have the spells and talents pre-tbc so that would mean Paladins for exemple have 30 second seals again and the talents would be reverted to their pre-tbc state as well so that means no crusader strike for Paladins either. 
And then do same for when you hit TBC content the TBC variants unlock and do same for Wrath content.

and then about questmarkers on minimap and quest objectives on the map those could be turned off before you hit Wrath/ICC content. Maybe turn those on for when you hit ICC raid and same with dungeon finder. Of course these would all be toggleable because I understand these ideas are not for everyone same with talents and questmarkers/objectives etc.

Also a last question, would you be thinking about doing a similar module for LegionCore 7.3.5. But instead it starts with Cata-MoP-WoD-Legion. I understand the Legion content there is pretty broken but maybe someday it will be good. At least the other content seems to be working.

**Comment by ZhengPeiRu21** [comment]
Hello! I am glad you are liking the module! Thank you for sharing these ideas.

There are two main reason why talents are not modified. The first is that I hope to minimize the need for any client modification - right now the module completely works without any modification except for changes to profession recipes, which are optional. Changing talents would require core changes and require a client patch. The second reason is that there is no way to change available talents based on player level and progression on the client (at least, not without extensive re-writing of the client - everything is possible with programming, but that is obviously outside this module's scope. Haha.)

Questmarkers on the minimap is correct behavior all the way back to Vanilla, so I do not think it would be accurate to disable at any point. (Please correct me if I am wrong about this.) Quest markers on the map can currently be disabled - this is handled by the optional_remove_quest_markers.sql file. This is the only optional file that is disabled by default, as I have received complaints about it accidentally being enabled and many prefer to keep it on. Like you, I personally like it off, because the game was not designed with this markers in mind - they were only added in 3.2, when very few new quests were still added.

Right now, there are no open source projects for higher expansions that are close to playable. In addition to the content not being present or scripted, the current open source projects for these expansions do not have fundamental features like correct processing of packets, so they are far from usable. I would very exciting to see a proper project with support for these, and would definitely be interesting to create a version of this module with support for them - maybe even a way to tie to to the Wrath client so that progress can start there and then continue into Cata and beyond through a character transfer. However, it may be many years until we reach the level where it is reasonable to start looking into this. ^_^

Please let me know if you have any further questions or find any areas of improvement to make to the module!
