### ISSUE TITLE
Not Sure where to put ot I have a question

### ISSUE THREAD

**Issue by tmyrdal** [ZhengPeiRu21/mod-individual-progression#370]
Do you think you can add the module "ARAC - All Races All Classes" to this pack?
That will have been awsome, as Im not getting it to work as to much errors come up.

**Comment by ZhengPeiRu21** [comment]
Thank you for reaching out. Unfortunately due to ARAC overwriting Spell.dbc, it is incompatible with Individual Progression when the optional files are used, so I'm not able to include it in the repack. It should be possible to use them together without the optional files, though there may be some issues (restored class quests not available for races that didn't originally have them, etc.)
