### ISSUE TITLE
Cannot teleport to northrend

### ISSUE THREAD

**Issue by AldebaraanMKII** [ZhengPeiRu21/mod-individual-progression#379]
On my level 80 characters, i'm unable to teleport with the .tele command to any location in Northrend. I'm also unable to reach there via Zeppelin and mage portals.

I noticed that EnablePlayerSettings was 0, so i set it to 1 and re-tested with no change.

**Comment by Grimfeather** [comment]
That's because of progression levels.
https://github.com/ZhengPeiRu21/mod-individual-progression/wiki/List-of-Progression-Tiers

If you're able to log into the database with HeidiSQL
you can set your progression level here: acore_characters / character_settings
set `Data` to at least 11. I believe that's the first phase of WotLK

**Comment by AldebaraanMKII** [comment]
Ok thank you. Changing it to 16 using HeidiSQL fixed the problem.
