### ISSUE TITLE
Npc_ipp_aq script prevents Dungeon 2 class set questline completion

### ISSUE THREAD

**Issue by bkmangx1** [ZhengPeiRu21/mod-individual-progression#39]
Hey, these 2 npcs are phased out until "AQ" progression, at the same time they are involved in dungeon set quest chain. That set is pre-raid/molten core tier.

https://www.wowhead.com/classic/npc=15282/aurel-goldleaf
https://www.wowhead.com/classic/npc=15270/huum-wildmane

As a result, this quest cannot be completed https://www.wowhead.com/classic/quest=8961/three-kings-of-flame because you cannot summon the Duke in Silithus without doing some quests from Aurel Goldleaf first.

**Comment by ZhengPeiRu21** [comment]
Thank you for reporting. This is currently intentional, as Dungeon Set 2 was not added until patch 1.10, so it is not available until later Vanilla progression. This is AQ content that is most appropriately done with the rest of the AQ content after BWL. The other NPCs in this area provide AQ catch-up gear and catch-up quests, so it would feel unusual for just these two NPCs to be an exception.

However, on the other hand, I can also understand that players would not find much use for the gear at the time they have progressed far enough to unlock it. What are your thoughts as a player? Perhaps this should be a configurable option?

**Comment by bkmangx1** [comment]
I suppose config option would be the best solution. Players are able to get 6/8 parts of the set and it's frustrating to be unable to complete it after doing a very long and expensive quest chain.

Also I spotted 2 more npcs that are not phased out and offering AQ quests, maybe you should add them to the script.
https://www.wowhead.com/classic/npc=15500/keyl-swiftclaw#starts
https://www.wowhead.com/classic/npc=15498/windcaller-yessendra#starts

**Comment by ZhengPeiRu21** [comment]
Thanks for your input. I'll add this as a configurable option, and probably leave those NPCs unphased by default. Thank you for pointing out the unphased NPCs - I will check phasing and add it if they uncorrectly unphased.

**Comment by ZhengPeiRu21** [comment]
Thanks again for your insight. These changes have been implemented in https://github.com/ZhengPeiRu21/mod-individual-progression/commit/17e820ab2e5d552bb440bf08e3072f65554fd63a. These NPCs should now appear early by default, and a config option has been added.
