### ISSUE TITLE
[Bug] Incorrect description and stats of crafted items

### ISSUE THREAD

**Issue by Dezaimasu** [ZhengPeiRu21/mod-individual-progression#402]
In DB it's Quality=1, but in game it's green in the recipes list, it's green after it's crafted, it tells me "equipping this item will bind it to you" every time I try to equip it. But it won't give me any bonus stats, it will only give me the armor value from DB, not the one I can see on the item itself. It still shows "Binds when equipped" even after it's already equipped, and every time I try to re-equip it, it tells me "equipping this item will bind it to you" again.

From Tailoring:

**Heavy Linen Gloves**
Give 11 armor and no spirit.
![image](https://github.com/user-attachments/assets/f6da0262-4186-4657-a8b8-67820454b006)
![image](https://github.com/user-attachments/assets/8718c61b-b1d1-49f6-bf56-8f7f84c7a19f)
![image](https://github.com/user-attachments/assets/c69c7540-1ebb-492d-b471-7eec9065db8e)

**Brown Linen Pants**
Give 16 armor and no intellect.
![image](https://github.com/user-attachments/assets/05ddb1d7-090c-400d-a178-18517579f565)
![image](https://github.com/user-attachments/assets/3b0ae3cd-a4c6-409c-96eb-f3f34ea230f3)

All the changes from `item_changes.sql` are applied to DB, .dbc files are copied to Data\dbc server folder, patch-V.mpq is copied to Data game folder.

**Comment by Grimfeather** [comment]
You did not install the client patch-v file (correctly)
![Image2](https://github.com/user-attachments/assets/2b6d7dbc-51a2-4376-9465-b586a9992247)
![Image4](https://github.com/user-attachments/assets/8b74570a-16d7-4ad0-abdd-e9b920c3af8f)

those items are white. not green.
They are changed back to white, because that's what they were during vanilla wow.

Place the patch-v.mpq file in your client's Data folder.
and delete your cache files in your client's Cache\WDB\enUS folder.

**Comment by Dezaimasu** [comment]
@Grimfeather 
Yep, it was the cache, wasn't mentioned on How to Install page so I forgot to delete it. Thanks a lot.
