### ISSUE TITLE
Compilation error

### ISSUE THREAD

**Issue by ajgration** [ZhengPeiRu21/mod-individual-progression#410]
Hey guys. I'm doing a fresh install and finding I can't get my build to compile when I add this module.

I'm running the playerbots module too, so I'm compiling off this AC source https://github.com/liyunfan1223/azerothcore-wotlk

Using the latest version of visual studio 2022, so that's not the issue. Wondering if anyone else is having a similar issue and knows a fix? I'll attach the errors and output from VS.

![errors](https://github.com/user-attachments/assets/e99c6801-5a97-4cb4-8fe0-baf3207099b5)
[builderrors.txt](https://github.com/user-attachments/files/17624872/builderrors.txt)

**Comment by Grimfeather** [comment]
just to be sure, did you remove the -master tag from the module directory?

**Comment by ajgration** [comment]
Yeah mate. My build compiles fine with all my other modules too if I remove this one.

**Comment by Grimfeather** [comment]
I looked at the builderrors file and googled the fatal error in there.

https://stackoverflow.com/questions/7076494/fatal-error-c1001-an-internal-error-has-occurred-in-the-compiler

The solution given there is:
In order to solve it, I deleted my build folder (Output Directory as seen in Properties/General) and rebuilt the project.

**Comment by ajgration** [comment]
Thanks Grim, worked a charm.
