### ISSUE TITLE
Spiced Bread Recipe lvl 200

### ISSUE THREAD

**Issue by StraysFromPath** [ZhengPeiRu21/mod-individual-progression#43]
Cooking Recipe (usually lvl 1) Spiced Bread requires lvl 200 in cooking.

**Comment by ajgration** [comment]
I can answer this one. This is intentional as it was a catch-up mechanic added later. You'll notice the vanilla vendors have simple flour removed too.

Line 34 in "professions.sql"
-- Make Spice Bread learnable for completion's sake, but only after reaching a level when it will no longer allow skipping early cooking
UPDATE npc_trainer SET ReqSkillRank = 200 WHERE SpellID = 37836;

You can change it to SET ReqSkillRank to 1 if you'd like to revert it, but you'd have to update vendors to have simple flour again too. Those changes are in "vanilla_vendors.sql".

**Comment by StraysFromPath** [comment]
> I can answer this one. This is intentional as it was a catch-up mechanic added later. You'll notice the vanilla vendors have simple flour removed too.
> 
> Line 34 in "professions.sql" -- Make Spice Bread learnable for completion's sake, but only after reaching a level when it will no longer allow skipping early cooking UPDATE npc_trainer SET ReqSkillRank = 200 WHERE SpellID = 37836;
> 
> You can change it to "SET ReqSkillRank = 1" if you'd like to revert it, but you'd have to update vendors to have simple flour again too. Those changes are in "vanilla_vendors.sql".

Ah thank you for this very informed reply. I checked the wiki and you are right spiced bread recipe was added in 2.0.1 even though it is in wow classic.

As it is part of thanksgiving world event it can be a little awkward for lvl 1 recipe to require lvl 200 recipe so I will run your SQL thank you.

https://www.wowhead.com/wotlk/item=44837/spice-bread-stuffing
