### ISSUE TITLE
worldserver crash

### ISSUE THREAD

**Issue by blazersrng** [ZhengPeiRu21/mod-individual-progression#52]
Hi, can you take a look what is the cause?

https://gist.github.com/blazersrng/735cac1a43fe119b6c8072f04e82b7d5

AzerothCore rev. f8948253dd38+ 2022-12-10 13:20:16 +0700 (npcbots_3.3.5 branch) (Win64, RelWithDebInfo, Static) (worldserver-daemon)
OS Windows 7

**Comment by blazersrng** [comment]
I am using NPCBots branch, but their author said it is caused by the module. https://github.com/trickerer/Trinity-Bots/issues/289

**Comment by ZhengPeiRu21** [comment]
I have added a fix for this crash in https://github.com/ZhengPeiRu21/mod-individual-progression/commit/61e0901cc823aeea966c8db09929385e629c24c6. Please kindly note that because NPCBots appears to be passing a null reference to the ModifyDamage and ModifyHealing hooks that the NPCBots will not be impacted by Vanilla and TBC scaling and may be overpowered, but it should at least not crash. Please let me know if you see any more issues or if this fix does not resolve the problem.

**Comment by blazersrng** [comment]
Thank you for the update, I will test and report if I find any issues.

Yes, I'm aware that they are not being scaled by module, but have their own config options to modify damage/healing/hp. It is not an issue on small server where all players are on same expansion, I can edit bot config to make them deal 60% damage and such to match the player power.

**Comment by trickerer** [comment]
@ZhengPeiRu21 if you look closer at AuraEffect::HandlePeriodicHealAurasTick() where your ModifyHealReceived() is called from you may notice checks for caster existence. Caster _**can**_ be NULL there and it's not related to NPCBots. In this particular case it seem like spell is casted by item (caster = NULL, casterItemGUID == casterGUID)

**Comment by ZhengPeiRu21** [comment]
> @ZhengPeiRu21 if you look closer at AuraEffect::HandlePeriodicHealAurasTick() where your ModifyHealReceived() is called from you may notice checks for caster existence. Caster _**can**_ be NULL there and it's not related to NPCBots. In this particular case it seem like spell is casted by item (caster = NULL, casterItemGUID == casterGUID)

Thank you very much, I missed that! I will correct my comments.
