### ISSUE TITLE
[Possible Unintended Behaviour] Elites Outside Instances are Overscaled

### ISSUE THREAD

**Issue by StraysFromPath** [ZhengPeiRu21/mod-individual-progression#61]
To try to enter places like Wailing Caverns, Deadmines, and Gnomeregan you must slog through 50-100 full powered elites to get to the instance door.

Once inside, the scaling module for individual play makes the instance mobs much easier than the outside.

This creates a weird block where getting inside is harder than clearing.

**Comment by bkmangx1** [comment]
It's not related to this module, scaling is handled by [mod-autobalance](https://github.com/azerothcore/mod-autobalance). You can scale creatures in open world by adding their IDs to `AutoBalance.ForcedIDXX ` and changing `AutoBalance.DungeonsOnly` to 0.

**Comment by ZhengPeiRu21** [comment]
> It's not related to this module, scaling is handled by [mod-autobalance](https://github.com/azerothcore/mod-autobalance). You can scale creatures in open world by adding their IDs to `AutoBalance.ForcedIDXX ` and changing `AutoBalance.DungeonsOnly` to 0.

Yes, this is correct explanation. mod-individual-progression by itself does not provide any sort of scaling, so all mobs should have correct Vanilla accurate stats. I will investigate updating the default autobalance configuration in the repack for users who are using it, but I am for now going to close this issue because it is not related to the Individual Progression module.
