### ISSUE TITLE
SQL - class_trainers.sql

### ISSUE THREAD

**Issue by mtompkins** [ZhengPeiRu21/mod-individual-progression#62]
This SQL fails, and it looks to be from an incorrect classMask below (40 vs 32) or perhaps a check to see if the value already exists?
```
DELETE FROM `playercreateinfo_skills` WHERE `raceMask`=0 AND `classMask`=40 AND `skill`=118;
INSERT INTO `playercreateinfo_skills` (`raceMask`, `classMask`, `skill`, `rank`, `comment`) VALUES (0, 32, 118, 0, 'Dual Wield');
```

**Comment by xmosyo** [comment]
*It's possible that there are no rows in the playercreateinfo_skills table that match the criteria specified in the DELETE statement In this case, the DELETE statement will not delete any rows and will not return an error.
*It's also possible that the classMask value in the DELETE statement is incorrect and that the correct value should be 32, as specified in the INSERT statement. If this is the case, the DELETE statement will not delete any rows because no rows match the specified criteria.
* It might be helpful to check the data in the playercreateinfo_skills table to see if there are any rows that match the criteria specified in the DELETE statement, and to check if there are any rows with a classMask value of 32.

**Comment by ZhengPeiRu21** [comment]
Thank you for reporting the issue, this is fixed in https://github.com/ZhengPeiRu21/mod-individual-progression/commit/00f55ad0510b7e5ba6677344b9304207b6172bf9.
