### ISSUE TITLE
Spell/NPC: Summon Compact Harvest Reaper Massively Overscaled

### ISSUE THREAD

**Issue by StraysFromPath** [ZhengPeiRu21/mod-individual-progression#64]
![image](https://user-images.githubusercontent.com/119371540/208328684-10e393d8-4fd4-44fe-87d3-785e260b0614.png)

This creature is summoned by lvl 15s in Barrens and lvl 24s in Stonetalon but it is a level ?? with 3000+ HP that hits for 80 and does not despawn when its creator dies. Without GM commands its 100% death.

**Comment by ajgration** [comment]
can confirm. also found this issue.

**Comment by ZhengPeiRu21** [comment]
This appears to be due to a missing feature in AzerothCore, so this creature always uses the Stranglethorn stat values rather than scaling as it should. Here is the related AC issue: https://github.com/azerothcore/azerothcore-wotlk/issues/8945

**Comment by ZhengPeiRu21** [comment]
As a temporary fix for this issue until the core AC problem is resolved, I have reverted this creature to always summon the lower-level version. Having easy enemies in Stranglethorn is preferable to unbeatable enemies in lower level areas. The fix is https://github.com/ZhengPeiRu21/mod-individual-progression/commit/1507adde010cb0502cf5d5be01d0e42099a41ed8.
