### ISSUE TITLE
Dungeon Finder in Progression

### ISSUE THREAD

**Issue by Vanheden** [ZhengPeiRu21/mod-individual-progression#89]
Hello!

I noticed when you got level 58-60 ish and you're still on Molten Core aka first Part of your Progression the Dungeon Finder points you towards TBC dungeons and not Vanilla.

**Comment by zaicopx** [comment]
Use this: https://github.com/azerothcore/mod-rdf-expansion

**Comment by ZhengPeiRu21** [comment]
> 

Thank you for sharing this solution. I'll see if I can integrate this into the module, since this does seem like an essential feature.

**Comment by ZhengPeiRu21** [comment]
I've implemented a solution in https://github.com/ZhengPeiRu21/mod-individual-progression/commit/c9a5d7f128296070ac3d4e0397b8be54f9f23506. Players will now be placed in appropriate random dungeon queues for their progression even when above level 58. Note that because of client limitations, players can still choose Random TBC Dungeon, but it will queue them for an appropriate dungeon based on progression instead. Please let me know if you see any issues!

**Comment by Vanheden** [comment]
Wow that was fast thanks!
