### ISSUE TITLE
after update got a lot of errors

### ISSUE THREAD

**Issue by Parkan1986** [ZhengPeiRu21/mod-individual-progression#90]
After  recompiling of new core updates and progression module after reapplying vanilla_creature_value server shows a lot of errors in console on world launch

 I am using those sources which were updated today https://github.com/trickerer/AzerothCore-wotlk-with-NPCBots
![image](https://user-images.githubusercontent.com/30984138/219885128-ff431805-be4d-4439-863d-76aa484cee95.png)

**Comment by Day36512** [comment]
I can confirm same errors.

**Comment by ZhengPeiRu21** [comment]
Thank you for sharing the messages - I will get these fixed today.

**Comment by ZhengPeiRu21** [comment]
This should now be fixed in https://github.com/ZhengPeiRu21/mod-individual-progression/commit/772e83325e05ed93e4e7f3cf78fa8c3cb584aba8. You may need to re-install from a fresh DB to properly resolve the issues - if you need a script to just fix these issues while preserving the database let me know and I will put something together for you. Sorry about introducing the issue!

**Comment by blazersrng** [comment]
Yeah it doesn't work on existing database. 

>  Reapplying update "vanilla_creature_values.sql" '6C8DD9C' -> '46A24FE' (it changed)...
> ERROR 1064 (42000) at line 24080 in file: 'E:\AzerothcoreSrc\data\sql\custom\db_world\vanilla_creature_values.sql': You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '= 1, `maxlevel` = 1, `speed_walk` = 1.0, `DamageModifier` = 1.3 WHERE `entry`=16' at line 1♪◙

Would be nice if you could provide a query to fix this without dropping whole db.
